version: "3.8"

volumes:
  nextcloud_data:
  db_data:

services:
  db:
    image: mariadb:10.11
    container_name: nextcloud_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=supersecure
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - npmnet

  nextcloud:
    image: nextcloud
    container_name: nextcloud_app
    restart: always
    environment:
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    volumes:
      - nextcloud_data:/var/www/html
    expose:
      - "80"
    networks:
      - npmnet
    depends_on:
      - db

networks:
  npmnet:
    external: true
